CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE TABLE public.authors (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    bio text
);

CREATE TABLE public.categories (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL UNIQUE
);

CREATE TABLE public.books (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    isbn character varying(255) NOT NULL UNIQUE,
    title character varying(255) NOT NULL,
    description text,
    total_copies integer NOT NULL,
    available_copies integer NOT NULL,
    shelf_location character varying(255),
    cover_image_url character varying(255),
    added_date date
);

CREATE TABLE public.book_authors (
    book_id bigint NOT NULL REFERENCES public.books(id),
    author_id bigint NOT NULL REFERENCES public.authors(id),
    PRIMARY KEY (book_id, author_id)
);

CREATE TABLE public.book_categories (
    book_id bigint NOT NULL REFERENCES public.books(id),
    category_id bigint NOT NULL REFERENCES public.categories(id),
    PRIMARY KEY (book_id, category_id)
);

CREATE TABLE public.loans (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL REFERENCES public.users(id),
    book_id bigint NOT NULL REFERENCES public.books(id),
    checkout_date date NOT NULL,
    due_date date NOT NULL,
    return_date date,
    status character varying(255) NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED', 'OVERDUE'))
);

CREATE TABLE public.reservations (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL REFERENCES public.users(id),
    book_id bigint NOT NULL REFERENCES public.books(id),
    reservation_date date NOT NULL,
    status character varying(255) NOT NULL CHECK (status IN ('PENDING', 'FULFILLED', 'CANCELLED'))
);

CREATE TABLE public.fines (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    loan_id bigint NOT NULL REFERENCES public.loans(id) UNIQUE,
    amount numeric(10,2) NOT NULL,
    reason character varying(255) NOT NULL,
    payment_status character varying(255) NOT NULL CHECK (payment_status IN ('UNPAID', 'PAID'))
);

CREATE TABLE public.users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL UNIQUE,
    password character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    phone_number character varying(255),
    role character varying(255) NOT NULL CHECK (role IN ('ADMIN', 'MEMBER')),
    account_status character varying(255) NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE', 'BLOCKED')),
    created_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO public.users (email, password, full_name, role) VALUES
('admin@example.com', crypt('admin123', gen_salt('bf')), 'Admin User', 'ADMIN');